@startuml
'https://plantuml.com/state-diagram

scale 350 width
hide empty description
[*] --> CasillaVacia
CasillaVacia --> CasillaOcupada : construirEdificio
CasillaVacia --> CasillaOcupada : colocarUnidad

@enduml