@startuml

class AlgoStar {
    - jugadores : Jugador

    + AsignarJugador(nombre : String, color : String, imperio : Imperio)
    + revisarJugador(jugadorARevisar : Jugador)
}

class Jugador {
    - nombre : String
    - color : String
    - imperio : Imperio

    + Jugador(nombre : String, color : String, imperio : Imperio)
    - verificarLargoDeNombre(nombre : String)
    - verificarRespectoDe(jugador : Jugador)

}

AlgoStar *-- "0..8" Jugador

@enduml