@startuml Imperio
interface Imperio {

    + construir(a: Construccion)
    + pasarTurno()
}
class Zerg {
    - arrayConstrucciones: Zangano

    + construir(a: Construccion)
    + pasarTurno()
}

class Protoss {
    - arrayConstrucciones: Construccion

    + construir(a: Construccion)
    + pasarTurno()
}

Zerg <|.. Imperio
Protoss <|.. Imperio


@enduml