@startuml


class Tablero{
   - mapa: Grafo

   + adyascentes(posicion)
   + distancia(posicion): Colection
}

class Grafo{
   - diccionarioDeDiccionarios: HashMap

   + dijkstra(posicion)
   + adyascentes(nodo)
}

Tablero *--"1" Grafo


@enduml