@startuml

class Zergs {
    + terminarTurno()
    + construirCriadero(unZangano : Zangano) : Criadero
    + construirExtractor(unZangano : Zangano) : Extractor
    + construirReservaDeReproduccion(unZangano : Zangano) : ReservaDeReproduccion
    + construirGuarida(unZangano : Zangano) : Guarida
    + construirEspiral(unZangano : Zangano) : Espiral
}

class Recurso {
    - cantidad
    + Recurso()
    + Recurso(cantidadInicial : int)
    + consumir(cantidad : int)
    + depositar(cantidad : int)

}

abstract class Edificio {
    - posicion : Coordenadas
    - requisitosDeNodo : NodoCompatible
    - estado : EstadoEdificio
    - vida : Vida
    + accionDeTurno()
    + esCompatible(unTerreno : Terreno, unRecurso : NodoRecurso) : Bool
    + recibirDanio(cantidad : int)
}

class Zangano {
    - posicion : Coordenadas
    + Zangano()
    + Zangano(posicion : Coordenadas)
    + extraerMineral()
    + accionDeTurno()
}

interface Turno {
    {abstract} + accionDeTurno()
}

interface Daniable {
    {abstract} + recibirDanio(cantidad : int)
}

class Criadero {
    - maxLarvas : int
    - cantidadLarvas : int
    - costoMineral : int
    + Criadero(ubicacion : NodoCompatible, mineral : Recurso)
    + accionDeTurno()
    + criarZangano() : Zangano
    - aumentarLarvas()
}

class Extractor {
    - maxZanganos : int
    - trabajadores : Zangano
    + Extractor(requisitos : NodoCompatible, gasVespeno : Recurso)
    + accionDeTurno()
    + recibirZangano(unZangano : Zangano)
}

class ReservaDeReproduccion {
    + ReservaDeReproduccion(requisitos : NodoCompatible)
}

class Guarida {
    + Guarida(requisitos : NodoCompatible)
}

class Espiral {
    + Espiral(requisitos : NodoCompatible)
}

class CantidadDeRecursoInsuficiente <<exception>> {
}

class CriaderoSinLarvas <<exception>> {
}

Zergs -left> "3" Recurso
Zergs -right-> "*" Edificio
Zergs -up-> "*" Zangano

Daniable <|.down. Edificio
Turno <|.left. Zangano
Turno <|.. Edificio

Edificio <|-- Criadero
Edificio <|-- Extractor
Edificio <|-- ReservaDeReproduccion
Edificio <|-- Guarida
Edificio <|-- Espiral

CantidadDeRecursoInsuficiente <.. Recurso
CriaderoSinLarvas <.up. Criadero

@enduml